### ISSUE TITLE
About the results of the experiment on "tinysleepnet"

### ISSUE THREAD

**Issue by liu-yuyun** [gist-ailab/SleePyCo#1]
Hello, may I ask if the experimental results of Tinysleep in your paper are directly run by the author of open source code? His code I ran directly got poor results on edf_2013 dataset.

**Comment by SeongjuLee** [comment]
We used the experimental results of TinySleepNet which were reported in the TinySleepNet paper. I will let you know the results which i directly run in the repo.

**Comment by lyy66666** [comment]
Thank you for answering my doubts. And can you tell me what version of pytorch you are using? I am also using a 30 series graphics card, it should be suitable for your environment, if it is convenient, can you share the yml environment configuration file generated by conda?

**Comment by SeongjuLee** [comment]
We ran their TinySleepNet implementation. We got similar results in Sleep-EDF-2013, while got poor results in Sleep-EDF-2018. It seems that they have problems on reproduction.
