### ISSUE TITLE
accuracy

### ISSUE THREAD

**Issue by mochenxin000** [gist-ailab/SleePyCo#11]
Hello, I'm a newbie. I reproduced your work. Very interested. But I would like to know how the final accuracy of the model's 20 fold cross-validation is calculated. Is it the highest fold and then average it?

**Comment by SeongjuLee** [comment]
The final accuracy is calculated using the confusion matrix, which is the summation of the test confusion matrices across all folds. Note that the test confusion matrix for each fold is obtained by evaluating the model, which has the best result on the validation set, on the test set at the corresponding fold (for fair evaluation).
