### ISSUE TITLE
SLEEP-EDF:Whether the dataset is subject to data filtering?

### ISSUE THREAD

**Issue by SunQuantao0** [gist-ailab/SleePyCo#12]
Hello I would like to ask if data filtering is done using the sleepedf dataset, does it use all the data in it? In that sleepedf2013 it looks like you selected 39 data, is his complete dataset 44?

**Comment by SeongjuLee** [comment]
Thank you for your interest in our work!
The total number of recordings in the Sleep-EDF 2013 version is 61. Following previous works, we selected the SC recordings, which include 39 recordings. The remaining ones are ST subjects.

**Comment by SunQuantao0** [comment]
Nice to hear back from you, thanks for the reply!


---- Replied Message ----
| From | Seongju ***@***.***> |
| Date | 11/22/2024 18:37 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [gist-ailab/SleePyCo] SLEEP-EDF:Whether the dataset is subject to data filtering? (Issue #12) |

Thank you for your interest in our work!
The total number of recordings in the Sleep-EDF 2013 version is 61. Following previous works, we selected the SC recordings, which include 39 recordings. The remaining ones are ST subjects.
