### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by shijie-dev** [gist-ailab/SleePyCo#2]
Hello, is the path filled in incorrectly? Or is the sequence length not filled in? Or is it because the shuffle parameters are set incorrectly?
      I hope you can answer my questions

**Comment by SeongjuLee** [comment]
Hello, the error may be occurred because the dataset, which is processed into npz format, is empty or located on wrong directory.
Did you execute ```python prepare_sleep-edf-201X.py``` after download?
If you provide detailed errors, it will help me to answer your question.
