### ISSUE TITLE
Hello, I am running into an issue "AttributeError: module 'numpy' has no attribute 'int'."

### ISSUE THREAD

**Issue by Brandoncheaa** [gist-ailab/SleePyCo#3]
I have finished downloading the dataset and am now processing .edf into .npz.

![Screenshot 2024-02-02 140038](https://github.com/gist-ailab/SleePyCo/assets/1521779/f677da34-3d54-4018-8830-e293335aead5)

**Comment by Brandoncheaa** [comment]
I would also like to address that this only happens with the sleep-edf-2018, I think for sleep-edf-2013 nothing is happening but thats another problem.

**Comment by Brandoncheaa** [comment]
Also this issue in the picture is mainly for sleep-edf-2018. I'm not sure about the 2013 dataset, I am however curious I ran "python prepare_sleep-edf-2013.py" and didn't get any errors but when I went to the directory sleep-edf-2013->npz->Fpz-Cz->I was expecting to see the converted edf to npz files but I only saw info.some sort of file. Do you have any idea as to why that's the case as well?

**Comment by Brandoncheaa** [comment]
Nevermind, issue has been solved. I changed the version of numpy to 1.19.5 and it solved the issue.

**Comment by SeongjuLee** [comment]
Thank you for leaving comments.
I will update the required version of numpy in README.md.
