### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Brandoncheaa** [gist-ailab/SleePyCo#5]
I've reproduced your results however I wanted to test datasets that the algorithm hasn't been trained on just to see how the accuracy holds up. Specifically I'm looking at the DREAMS-subject dataset you can find it here "https://zenodo.org/records/2650142"-DatabaseSubjects.rar and imported the dataset into dset. Could you possibly help me test it or guide me in someway that I can write a script that will test it. I am doing my senior project on implementing your algorithm and will be testing it against our device that will generate real world data so any information in regards to formatting will be of large help!

**Comment by Brandoncheaa** [comment]
Additionally how do I go about producing the hypnogram visuals for the data, do you have a script that you can provide for that?

**Comment by SeongjuLee** [comment]
Thank you for having interests on our work!, and we apologize for late response.
We add source code to test on a sample of custom data, refer to ```test_custom.py```.
Also, we add source code to draw hypnogram in ```./tools```.
Have a good day!

**Comment by Brandoncheaa** [comment]
Thank you for getting back to me, I appreciate your assistance.
